### PR TITLE
updated version to newest release

### PR DESCRIPTION
**Pull request by pfrubby**
updated version and checksums to newest release

### CODE REVIEW

**Comment by BWalti** [comment]
Hello and thanks for the PR! Funny: today was my last day at work where I needed to use abaclient for time bookings, so .. I am going to merge this PR and I believe I still have to push the generated packages manually IIRC, but I will have to do this at my desktop (currently on mobile).
Nevertheless I wanted to ask you if you'd like to take over this repository and chocolatey package as I am probably not investing a lot of effort in the future 🙂

**Comment by BWalti** [comment]
Hello and thanks for the PR! Funny: today was my last day at work where I needed to use abaclient for time bookings, so .. I am going to merge this PR and I believe I still have to push the generated packages manually IIRC, but I will have to do this at my desktop (currently on mobile).
Nevertheless I wanted to ask you if you'd like to take over this repository and chocolatey package as I am probably not investing a lot of effort in the future 🙂

**Comment by BWalti** [comment]
Oh it got pushed automatically. Just with an older version number.. well there is that 🙂

**Comment by pfrubby** [comment]
Hi Beat :)
We'll gladly take the repo and chocolatey package off of your hands, but I think we'd need some further instructions or an introduction on how to maintain it in the future, since we haven't really worked on or with any chocolatey package thus far.

Let me know if you're interested in a short exchange and hand-over, for instance via a quick call!

**Comment by BWalti** [comment]
yeah, we can do this :)
I don't know a lot about these packages either though. I just worked through some kind of tutorial (e.g., the [docs](https://docs.chocolatey.org/en-us/create/create-packages)) at one place and as soon as it "worked" it was good enough for me. I'd say this specific package could still improve in "Versioning". As I basically just want to use the version of the "installer" also for the package (maybe with increments on revision if I need to fix some details or something).

May I send you an email to your git commit email address at your working place with my phone number etc.? Greetings to Christian H. btw ;)

**Comment by pfrubby** [comment]
I see, then I assume it can't be too hard to adopt, right? ;)
Looking forward to your email!

**Pull request merged**
